### ISSUE TITLE
First edition vs second

### ISSUE THREAD

**Issue by ijean** [SoftMoore/CPRL#1]
Hello,

I have the second edition of your *Introduction to Compiler Design* book and was wondering what are the differences between the first and second edition. It will be great if you can add a few lines about the difference between the two editions in the Readme.

Can I use the first edition with the latest code from this repository or do I need to use some older version ?

Thanks,
Jean

**Comment by SoftMoore** [comment]
Jean,

Thanks for the suggestion.  The changes to the second edition are outlined in the Preface on page xv of the second edition.  Unfortunately I don't have a detailed list.  However, the code on GitHub can be used with either edition.  I have resisted making any changes that would invalidate the first edition.

You might be interested to know about a future change.  I am planning to modify the Windows and bash script files so that they use Java modules and the module path rather than the class path.  While the books briefly mentions Java modules, the actual use of modules was not a requirement.

FYI, there is also a Kotlin version of the book that closely parallels the second edition of the Java version.  See the [CPRL-Kt](https://github.com/SoftMoore/CPRL-Kt) repository for more information.

**Comment by ijean** [comment]
Thanks for the quick answer.
